apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-test
spec:
  template:
    spec:
      containers:
      - image: 192.168.0.189:5000/busybox
        #image: <lan-host>:<port>/<image-name>:<tag>
        imagePullPolicy: IfNotPresent
        name: flask
status: {}