apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-test
spec:
  template:
    spec:
      containers:
      - image: 192.168.0.189:5000/busybox:latest
        #image: <lan-host>:<port>/<image-name>:<tag>
        nodeName: c1-node1
        imagePullPolicy: Always
        name: flask
status: {}