apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: temp2
  name: temp2
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - 'echo "spud wicker noodle!" && sleep 1d'
    image: 192.168.0.189/alpine:latest
    name: temp2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
