apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: temp
  name: temp
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep
    - 1d
    image: 192.168.0.189:5000/busybox
    name: temp
    resources: {}
  nodeName: c1-node1
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
