apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: temp2
  name: temp2
spec:
  nodeName: c1-node1 
  containers:
  - args:
    - /bin/sh
    - -c
    - echo "spud wicker!" && sleep 1d
    image: 192.168.0.189:5000/busybox:latest
    imagePullPolicy: Always
    name: temp2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
