apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
labels:
- includeSelectors: true
  pairs:
    app: kustomize-test
resources:
- deploy-kustomize-test.yaml
- svc-kustomize-test.yaml
commonAnnotations:
  app: custom-anno
namePrefix: kustom-
nameSuffix: v1
configMapGenerator:
- name: my-config
  files:
  - properties.txt
